"""Add legal page versions and channel-specific marketing consent.

Revision ID: 0008
Revises: 0007
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Adopt the Supabase-managed table when it already exists, while ensuring
    # fresh local and test databases receive the same minimum schema.
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS legal_pages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            slug TEXT NOT NULL,
            locale TEXT NOT NULL,
            title TEXT NOT NULL,
            content TEXT NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (slug, locale)
        )
        """
    )
    op.execute("ALTER TABLE legal_pages ADD COLUMN IF NOT EXISTS version TEXT")
    op.execute("UPDATE legal_pages SET version = 'v1' WHERE version IS NULL")
    op.alter_column("legal_pages", "version", nullable=False)

    # Preserve the existing general consent as email consent. Push consent is
    # a separate purpose and therefore starts disabled for every user.
    op.alter_column(
        "users",
        "marketing_consent",
        new_column_name="marketing_email_consent",
    )
    op.alter_column(
        "users",
        "marketing_consent_updated_at",
        new_column_name="marketing_email_consent_updated_at",
    )
    op.add_column(
        "users",
        sa.Column(
            "marketing_push_consent",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column(
        "users",
        sa.Column("marketing_push_consent_updated_at", sa.DateTime(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("users", "marketing_push_consent_updated_at")
    op.drop_column("users", "marketing_push_consent")
    op.alter_column(
        "users",
        "marketing_email_consent_updated_at",
        new_column_name="marketing_consent_updated_at",
    )
    op.alter_column(
        "users",
        "marketing_email_consent",
        new_column_name="marketing_consent",
    )
    # Keep the adopted legal content table, but undo the column owned by this revision.
    op.drop_column("legal_pages", "version")
